### PR TITLE
Save primitives from erasure (Scala2 only)

### PR DESCRIPTION
**Pull request by SamTheisens**
This PR attempts to address the issue that optional and iterable Java primitive types e.g. `Option[Int]`, `Seq[Boolean]` are lost in translation as described in https://github.com/swagger-akka-http/swagger-scala-module/issues/117.

Note that this implementation depends on scala reflection and therefore does not work in Scala 3. There is a stub method `ErasureHelper.erasedOptionalPrimitives(cls: Class[_]): Map[String, Class[_]]` that would need to be implemented using macros(?).
I may have a stab at that later, but I'm completely new to Scala 3 or macros for that matter. So if someone else know how to do this, help with that would be much appreciated!

### CODE REVIEW

**Comment by pjfanning** [comment]
Thanks - I'll merge this but I'll probably need to do something to get the tests to run for the scala3 build, even if they will have different assertion expectations. Scala3 version of this lib is not yet widely used.

**Comment by pjfanning** [comment]
@SamTheisens this change doesn't work as expected with swagger-akka-http. I have updated the sample - https://github.com/pjfanning/swagger-akka-http-sample - to use the swagger-scala-module v2.7.0.
This upgrade breaks the addOption support. The sample has relied on adding a Schema annotation to the Option[Int] param.  With and without this annotation, the swagger doc is now being generated without the int typing. I haven't spent much time debugging it but I've tried it a few times and it definitely seems to be broken.

Swagger-akka-http may need to be changed to help the scala-reflect stuff to work. I think the current code passes around Java class instances and this possibly stops the scala-reflect code getting proper access to do its thing.

**Comment by SamTheisens** [comment]
> 

@pjfanning that's too bad. I'll have a look as well.

**Comment by pjfanning** [comment]
@SamTheisens I fixed the issue with the swagger annotations being ignored in https://github.com/swagger-akka-http/swagger-scala-module/pull/168 and did a v2.7.1 release. The new erasure code still does not work in swagger-akka-http-sample but at least the sample now works again when the swagger annotations are used.

**Comment by SamTheisens** [comment]
> @SamTheisens I fixed the issue with the swagger annotations being ignored in #168 and did a v2.7.1 release. The new erasure code still does not work in swagger-akka-http-sample but at least the sample now works again when the swagger annotations are used.

I've found out that the reflection doesn't work for case classes that are defined nested inside an object. Trying to figure out if and how that can be fixed.

**Comment by pjfanning** [comment]
I've reproduced the issue with inner classes. It would be great to support inner classes but if necessary, we can document that the reflection support only works with classes that are not inner classes.

On the Scala 3 side of things, I've used this lib before - https://github.com/gzoller/scala-reflection - it might be an option here.

**Comment by SamTheisens** [comment]
> I've reproduced the issue with inner classes. It would be great to support inner classes but if necessary, we can document that the reflection support only works with classes that are not inner classes.
> 
> On the Scala 3 side of things, I've used this lib before - https://github.com/gzoller/scala-reflection - it might be an option here.

I think I've found a solution for the inner classes https://github.com/swagger-akka-http/swagger-scala-module/pull/169
It feels hacky, but I guess that's the nature of reflection.

**Pull request merged**
